### ISSUE TITLE
Incorrect judgment log level

### ISSUE THREAD

**Issue by binsee** [huan/sidecar#28]
When logLevel is equal to info, verbose logs should not be output

https://github.com/huan/sidecar/blob/ebef298a3a521ed2660e82c9c485240bcdd3dce3/src/agent/templates/libs/log.cjs#L5-L30

```
if (logLevel >= levelTable.verbose)
if (logLevel >= levelTable.silly)

// -->

if (logLevel <= levelTable.verbose)
if (logLevel <= levelTable.silly)

```

**Comment by huan** [comment]
Good catch!

A PR will be welcome.

**Comment by binsee** [comment]
After unit testing, there should be no problem here, maybe my code is wrong.
So close this issue
